/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as CartRouteImport } from './routes/cart'
import { Route as ConsegnatoRouteImport } from './routes/consegnato'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as DownloadRouteImport } from './routes/download'
import { Route as LockRouteImport } from './routes/lock'
import { Route as PagaRouteImport } from './routes/paga'
import { Route as PaidRouteImport } from './routes/paid'
import { Route as ProductsRouteImport } from './routes/products'
import { Route as ShopifyRouteImport } from './routes/shopify'
import { Route as ProductsIndexRouteImport } from './routes/products.index'
import { Route as ProductsHandleRouteImport } from './routes/products.$handle'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const CartRoute = CartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => rootRouteImport,
} as any)
const ConsegnatoRoute = ConsegnatoRouteImport.update({
  id: '/consegnato',
  path: '/consegnato',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const DownloadRoute = DownloadRouteImport.update({
  id: '/download',
  path: '/download',
  getParentRoute: () => rootRouteImport,
} as any)
const LockRoute = LockRouteImport.update({
  id: '/lock',
  path: '/lock',
  getParentRoute: () => rootRouteImport,
} as any)
const PagaRoute = PagaRouteImport.update({
  id: '/paga',
  path: '/paga',
  getParentRoute: () => rootRouteImport,
} as any)
const PaidRoute = PaidRouteImport.update({
  id: '/paid',
  path: '/paid',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsRoute = ProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopifyRoute = ShopifyRouteImport.update({
  id: '/shopify',
  path: '/shopify',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsIndexRoute = ProductsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ProductsRoute,
} as any)
const ProductsHandleRoute = ProductsHandleRouteImport.update({
  id: '/$handle',
  path: '/$handle',
  getParentRoute: () => ProductsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/cart': typeof CartRoute
  '/consegnato': typeof ConsegnatoRoute
  '/contact': typeof ContactRoute
  '/download': typeof DownloadRoute
  '/lock': typeof LockRoute
  '/paga': typeof PagaRoute
  '/paid': typeof PaidRoute
  '/products': typeof ProductsRouteWithChildren
  '/shopify': typeof ShopifyRoute
  '/products/$handle': typeof ProductsHandleRoute
  '/products/': typeof ProductsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/cart': typeof CartRoute
  '/consegnato': typeof ConsegnatoRoute
  '/contact': typeof ContactRoute
  '/download': typeof DownloadRoute
  '/lock': typeof LockRoute
  '/paga': typeof PagaRoute
  '/paid': typeof PaidRoute
  '/shopify': typeof ShopifyRoute
  '/products/$handle': typeof ProductsHandleRoute
  '/products': typeof ProductsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/cart': typeof CartRoute
  '/consegnato': typeof ConsegnatoRoute
  '/contact': typeof ContactRoute
  '/download': typeof DownloadRoute
  '/lock': typeof LockRoute
  '/paga': typeof PagaRoute
  '/paid': typeof PaidRoute
  '/products': typeof ProductsRouteWithChildren
  '/shopify': typeof ShopifyRoute
  '/products/$handle': typeof ProductsHandleRoute
  '/products/': typeof ProductsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/cart'
    | '/consegnato'
    | '/contact'
    | '/download'
    | '/lock'
    | '/paga'
    | '/paid'
    | '/products'
    | '/shopify'
    | '/products/$handle'
    | '/products/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/cart'
    | '/consegnato'
    | '/contact'
    | '/download'
    | '/lock'
    | '/paga'
    | '/paid'
    | '/shopify'
    | '/products/$handle'
    | '/products'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/cart'
    | '/consegnato'
    | '/contact'
    | '/download'
    | '/lock'
    | '/paga'
    | '/paid'
    | '/products'
    | '/shopify'
    | '/products/$handle'
    | '/products/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  CartRoute: typeof CartRoute
  ConsegnatoRoute: typeof ConsegnatoRoute
  ContactRoute: typeof ContactRoute
  DownloadRoute: typeof DownloadRoute
  LockRoute: typeof LockRoute
  PagaRoute: typeof PagaRoute
  PaidRoute: typeof PaidRoute
  ProductsRoute: typeof ProductsRouteWithChildren
  ShopifyRoute: typeof ShopifyRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cart': {
      id: '/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof CartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/consegnato': {
      id: '/consegnato'
      path: '/consegnato'
      fullPath: '/consegnato'
      preLoaderRoute: typeof ConsegnatoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/download': {
      id: '/download'
      path: '/download'
      fullPath: '/download'
      preLoaderRoute: typeof DownloadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lock': {
      id: '/lock'
      path: '/lock'
      fullPath: '/lock'
      preLoaderRoute: typeof LockRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/paga': {
      id: '/paga'
      path: '/paga'
      fullPath: '/paga'
      preLoaderRoute: typeof PagaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/paid': {
      id: '/paid'
      path: '/paid'
      fullPath: '/paid'
      preLoaderRoute: typeof PaidRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products': {
      id: '/products'
      path: '/products'
      fullPath: '/products'
      preLoaderRoute: typeof ProductsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shopify': {
      id: '/shopify'
      path: '/shopify'
      fullPath: '/shopify'
      preLoaderRoute: typeof ShopifyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/': {
      id: '/products/'
      path: '/'
      fullPath: '/products/'
      preLoaderRoute: typeof ProductsIndexRouteImport
      parentRoute: typeof ProductsRoute
    }
    '/products/$handle': {
      id: '/products/$handle'
      path: '/$handle'
      fullPath: '/products/$handle'
      preLoaderRoute: typeof ProductsHandleRouteImport
      parentRoute: typeof ProductsRoute
    }
  }
}

interface ProductsRouteChildren {
  ProductsHandleRoute: typeof ProductsHandleRoute
  ProductsIndexRoute: typeof ProductsIndexRoute
}

const ProductsRouteChildren: ProductsRouteChildren = {
  ProductsHandleRoute: ProductsHandleRoute,
  ProductsIndexRoute: ProductsIndexRoute,
}

const ProductsRouteWithChildren = ProductsRoute._addFileChildren(
  ProductsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  CartRoute: CartRoute,
  ConsegnatoRoute: ConsegnatoRoute,
  ContactRoute: ContactRoute,
  DownloadRoute: DownloadRoute,
  LockRoute: LockRoute,
  PagaRoute: PagaRoute,
  PaidRoute: PaidRoute,
  ProductsRoute: ProductsRouteWithChildren,
  ShopifyRoute: ShopifyRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
